-- 创建region表
CREATE TABLE IF NOT EXISTS region (
    tid INTEGER PRIMARY KEY AUTOINCREMENT,
    code TEXT not NULL,
    name TEXT not NULL,
    desc TEXT,
    router TEXT,
    pid INTEGER not NULL
   
);

-- 创建索引以提高查询性能
CREATE INDEX IF NOT EXISTS idx_region_code ON region(code);
CREATE INDEX IF NOT EXISTS idx_region_pid ON region(pid);

-- 插入region表数据（修正重复tid）
INSERT INTO region (tid, code, name, desc, router, pid) VALUES
(1, 'douga', '动画(主分区)', '', '/v/douga', 0),
(24, 'mad', 'MAD·AMV', '具有一定创作度的动/静画二次创作视频', '/v/douga/mad', 1),
(25, 'mmd', 'MMD·3D', '使用mmd（mikumikudance）和其他3d建模类软件制作的视频', '/v/douga/mmd', 1),
(47, 'voice', '短片·手书·配音', '追求个人特色和创意表达的自制动画短片、手绘（绘）及acgn相关配音', '/v/douga/voice', 1),
(210, 'garage_kit', '手办·模玩', '手办模玩的测评、改造或其他衍生内容', '/v/douga/garage_kit', 1),
(86, 'tokusatsu', '特摄', '特摄相关衍生视频', '/v/douga/tokusatsu', 1),
(253, 'acgntalks', '动漫杂谈', '以谈话形式对ACGN文化圈进行的鉴赏、吐槽、评点、解说、推荐、科普等内容', '/v/douga/acgntalks', 1),
(27, 'other', '综合', '以动画及动画相关内容为素材，包括但不仅限于音频替换、恶搞改编、排行榜等内容', '/v/douga/other', 1),
(13, 'anime', '番剧(主分区)', '', '/anime', 0),
(51, 'information', '资讯', '以动画/轻小说/漫画/杂志为主的资讯内容，PV/CM/特报/冒头/映像/预告', '/v/anime/information', 13),
(152, 'offical', '官方延伸', '以动画番剧及声优为主的EVENT/生放送/DRAMA/RADIO/LIVE/特典/冒头等', '/v/anime/offical', 13),
(32, 'finish', '完结动画', '已完结TV/WEB动画及其独立系列，旧剧场版/OVA/SP/未放送', '/v/anime/finish', 13),
(33, 'serial', '连载动画', '连载中TV/WEB动画，新剧场版/OVA/SP/未放送/小剧场', '/v/anime/serial', 13),
(167, 'guochuang', '国创(主分区)', '', '/guochuang', 0),
(153, 'chinese', '国产动画', '国产连载动画，国产完结动画', '/v/guochuang/chinese', 167),
(168, 'original', '国产原创相关', '以国产动画、漫画、小说为素材的二次创作', '/v/guochuang/original', 167),
(169, 'puppetry', '布袋戏', '布袋戏以及相关剪辑节目', '/v/guochuang/puppetry', 167),
(170, 'information', '资讯', '原创国产动画、漫画的相关资讯、宣传节目等', '/v/guochuang/information', 167),
(195, 'motioncomic', '动态漫·广播剧', '国产动态漫画、有声漫画、广播剧', '/v/guochuang/motioncomic', 167),
(3, 'music', '音乐(主分区)', '', '/v/music', 0),
(28, 'original', '原创音乐', '原创歌曲及纯音乐，包括改编、重编曲及remix', '/v/music/original', 3),
(31, 'cover', '翻唱', '对曲目的人声再演绎视频', '/v/music/cover', 3),
(30, 'vocaloid', 'VOCALOID·UTAU', '以vocaloid等歌声合成引擎为基础，运用各类音源进行的创作', '/v/music/vocaloid', 3),
(59, 'perform', '演奏', '乐器和非传统乐器器材的演奏作品', '/v/music/perform', 3),
(193, 'mv', 'MV', '为音乐作品配合拍摄或制作的音乐录影带（music video），以及自制拍摄、剪辑、翻拍mv', '/v/music/mv', 3),
(29, 'live', '音乐现场', '音乐表演的实况视频，包括官方/个人拍摄的综艺节目、音乐剧、音乐节、演唱会等', '/v/music/live', 3),
(130, 'other', '音乐综合', '所有无法被收纳到其他音乐二级分区的音乐类视频', '/v/music/other', 3),
(243, 'commentary', '乐评盘点', '音乐类新闻、盘点、点评、reaction、榜单、采访、幕后故事、唱片开箱等', '/v/music/commentary', 3),
(244, 'tutorial', '音乐教学', '以音乐教学为目的的内容', '/v/music/tutorial', 3),
(194, 'electronic', '电音(已下线)', '以电子合成器、音乐软体等产生的电子声响制作的音乐', '/v/music/electronic', 3),
(129, 'dance', '舞蹈(主分区)', '', '/v/dance', 0),
(20, 'otaku', '宅舞', '与acg相关的翻跳、原创舞蹈', '/v/dance/otaku', 129),
(154, 'three_d', '舞蹈综合', '收录无法定义到其他舞蹈子分区的舞蹈视频', '/v/dance/three_d', 129),
(156, 'demo', '舞蹈教程', '镜面慢速，动作分解，基础教程等具有教学意义的舞蹈视频', '/v/dance/demo', 129),
(198, 'hiphop', '街舞', '收录街舞相关内容，包括赛事现场、舞室作品、个人翻跳、freestyle等', '/v/dance/hiphop', 129),
(199, 'star', '明星舞蹈', '国内外明星发布的官方舞蹈及其翻跳内容', '/v/dance/star', 129),
(200, 'china', '中国舞', '传承中国艺术文化的舞蹈内容，包括古典舞、民族民间舞、汉唐舞、古风舞等', '/v/dance/china', 129),
(4, 'game', '游戏(主分区)', '', '/v/game', 0),
(17, 'stand_alone', '单机游戏', '以所有平台（pc、主机、移动端）的单机或联机游戏为主的视频内容，包括游戏预告、cg、实况解说及相关的评测、杂谈与视频剪辑等', '/v/game/stand_alone', 4),
(171, 'esports', '电子竞技', '具有高对抗性的电子竞技游戏项目，其相关的赛事、实况、攻略、解说、短剧等视频。', '/v/game/esports', 4),
(172, 'mobile', '手机游戏', '以手机及平板设备为主要平台的游戏，其相关的实况、攻略、解说、短剧、演示等视频。', '/v/game/mobile', 4),
(65, 'online', '网络游戏', '由网络运营商运营的多人在线游戏，以及电子竞技的相关游戏内容。包括赛事、攻略、实况、解说等相关视频', '/v/game/online', 4),
(173, 'board', '桌游棋牌', '桌游、棋牌、卡牌对战等及其相关电子版游戏的实况、攻略、解说、演示等视频。', '/v/game/board', 4),
(121, 'gmv', 'GMV', '由游戏素材制作的mv视频。以游戏内容或cg为主制作的，具有一定创作程度的mv类型的视频', '/v/game/gmv', 4),
(136, 'music', '音游', '各个平台上，通过配合音乐与节奏而进行的音乐类游戏视频', '/v/game/music', 4),
(19, 'mugen', 'Mugen', '以mugen引擎为平台制作、或与mugen相关的游戏视频', '/v/game/mugen', 4),
(36, 'knowledge', '知识(主分区)', '', '/v/knowledge', 0),
(201, 'science', '科学科普', '回答你的十万个为什么', '/v/knowledge/science', 36),
(124, 'social_science', '社科·法律·心理(原社科人文、原趣味科普人文)', '基于社会科学、法学、心理学展开或个人观点输出的知识视频', '/v/knowledge/social_science', 36),
(228, 'humanity_history', '人文历史', '看看古今人物，聊聊历史过往，品品文学典籍', '/v/knowledge/humanity_history', 36),
(207, 'business', '财经商业', '说金融市场，谈宏观经济，一起畅聊商业故事', '/v/knowledge/finance', 36),
(208, 'campus', '校园学习', '老师很有趣，学生也有才，我们一起搞学习', '/v/knowledge/campus', 36),
(209, 'career', '职业职场', '职业分享、升级指南，一起成为最有料的职场人', '/v/knowledge/career', 36),
(229, 'design', '设计·创意', '天马行空，创意设计，都在这里', '/v/knowledge/design', 36),
(122, 'skill', '野生技术协会', '技能党集合，是时候展示真正的技术了', '/v/knowledge/skill', 36),
(39, 'speech_course', '演讲·公开课(已下线)', '涨知识的好地方，给爱学习的你', '/v/technology/speech_course', 36),
(96, 'military', '星海(已下线)', '军事类内容的圣地', '/v/technology/military', 36),
(98, 'mechanical', '机械(已下线)', '机械设备展示或制作视频', '/v/technology/mechanical', 36),
(188, 'tech', '科技(主分区)', '', '/v/tech', 0),
(95, 'digital', '数码(原手机平板)', '科技数码产品大全，一起来做发烧友', '/v/tech/digital', 188),
(230, 'application', '软件应用', '超全软件应用指南', '/v/tech/application', 188),
(231, 'computer_tech', '计算机技术', '研究分析、教学演示、经验分享......有关计算机技术的都在这里', '/v/tech/computer_tech', 188),
(232, 'industry', '科工机械 (原工业·工程·机械)', '前方高能，机甲重工即将出没', '/v/tech/industry', 188),
(233, 'diy', '极客DIY', '炫酷技能，极客文化，硬核技巧，准备好你的惊讶', '/v/tech/diy', 188),
(189, 'pc', '电脑装机(已下线)', '电脑、笔记本、装机配件、外设和软件教程等相关视频', '/v/digital/pc', 188),
(190, 'photography', '摄影摄像(已下线)', '摄影摄像器材、拍摄剪辑技巧、拍摄作品分享等相关视频', '/v/digital/photography', 188),
(191, 'intelligence_av', '影音智能(已下线)', '影音设备、智能产品等相关视频', '/v/digital/intelligence_av', 188),
(234, 'sports', '运动(主分区)', '', '/v/sports', 0),
(235, 'basketball', '篮球', '与篮球相关的视频，包括但不限于篮球赛事、教学、评述、剪辑、剧情等相关内容', '/v/sports/basketball', 234),
(249, 'football', '足球', '与足球相关的视频，包括但不限于足球赛事、教学、评述、剪辑、剧情等相关内容', '/v/sports/football', 234),
(164, 'aerobics', '健身', '与健身相关的视频，包括但不限于瑜伽、crossfit、健美、力量举、普拉提、街健等相关内容', '/v/sports/aerobics', 234),
(236, 'athletic', '竞技体育', '与竞技体育相关的视频，包括但不限于乒乓、羽毛球、排球、赛车等竞技项目的赛事、评述、剪辑、剧情等相关内容', '/v/sports/culture', 234),
(237, 'culture', '运动文化', '与运动文化相关的视频，包络但不限于球鞋、球衣、球星卡等运动衍生品的分享、解读，体育产业的分析、科普等相关内容', '/v/sports/culture', 234),
(238, 'comprehensive', '运动综合', '与运动综合相关的视频，包括但不限于钓鱼、骑行、滑板等日常运动分享、教学、Vlog等相关内容', '/v/sports/comprehensive', 234),
(223, 'car', '汽车(主分区)', '', '/v/car', 0),
(245, 'racing', '赛车', 'f1等汽车运动相关', '/v/car/racing', 223),
(246, 'modifiedvehicle', '改装玩车', '汽车文化及改装车相关内容，包括改装车、老车修复介绍、汽车聚会分享等内容', '/v/car/modifiedvehicle', 223),
(247, 'newenergyvehicle', '新能源车', '新能源汽车相关内容，包括电动汽车、混合动力汽车等车型种类，包含不限于新车资讯、试驾体验、专业评测、技术解读、知识科普等内容', '/v/car/newenergyvehicle', 223),
(248, 'touringcar', '房车', '房车及营地相关内容，包括不限于产品介绍、驾驶体验、房车生活和房车旅行等内容', '/v/car/touringcar', 223),
(240, 'motorcycle', '摩托车', '骑士们集合啦', '/v/car/motorcycle', 223),
(227, 'strategy', '购车攻略', '丰富详实的购车建议和新车体验', '/v/car/strategy', 223),
(176, 'life', '汽车生活', '分享汽车及出行相关的生活体验类视频', '/v/car/life', 223),
(224, 'culture', '汽车文化(已下线)', '车迷的精神圣地，包括汽车赛事、品牌历史、汽车改装、经典车型和汽车模型等', '/v/car/culture', 223),
(225, 'geek', '汽车极客(已下线)', '汽车硬核达人聚集地，包括DIY造车、专业评测和技术知识分享', '/v/car/geek', 223),
(226, 'smart', '智能出行(已下线)', '探索新能源汽车和未来智能出行的前沿阵地', '/v/car/smart', 223),
(160, 'life', '生活(主分区)', '', '/v/life', 0),
(138, 'funny', '搞笑', '各种沙雕有趣的搞笑剪辑，挑战，表演，配音等视频', '/v/life/funny', 160),
(250, 'travel', '出行', '为达到观光游览、休闲娱乐为目的的远途旅行、中近途户外生活、本地探店', '/v/life/travel', 160),
(251, 'rurallife', '三农', '分享美好农村生活', '/v/life/rurallife', 160),
(239, 'home', '家居房产', '与买房、装修、居家生活相关的分享', '/v/life/home', 160),
(161, 'handmake', '手工', '手工制品的制作过程或成品展示、教程、测评类视频', '/v/life/handmake', 160),
(162, 'painting', '绘画', '绘画过程或绘画教程，以及绘画相关的所有视频', '/v/life/painting', 160),
(21, 'daily', '日常', '记录日常生活，分享生活故事', '/v/life/daily', 160),
(211, 'food', '美食(主分区)', '', '/v/food', 0),
(76, 'make', '美食制作(原[生活]->[美食圈])', '学做人间美味，展示精湛厨艺', '/v/food/make', 211),
(212, 'detective', '美食侦探', '寻找美味餐厅，发现街头美食', '/v/food/detective', 211),
(213, 'measurement', '美食测评', '吃货世界，品尝世间美味', '/v/food/measurement', 211),
(214, 'rural', '田园美食', '品味乡野美食，寻找山与海的味道', '/v/food/rural', 211),
(215, 'record', '美食记录', '记录一日三餐，给生活添一点幸福感', '/v/food/record', 211),
(217, 'animal', '动物圈(主分区)', '', '/v/animal', 0),
(218, 'cat', '喵星人', '喵喵喵喵喵', '/v/animal/cat', 217),
(219, 'dog', '汪星人', '汪汪汪汪汪', '/v/animal/dog', 217),
(220, 'panda', '大熊猫', '芝麻汤圆营业中', '/v/animal/panda', 217),
(221, 'wild_animal', '野生动物', '内有“猛兽”出没', '/v/animal/wild_animal', 217),
(222, 'reptiles', '爬宠', '鳞甲有灵', '/v/animal/reptiles', 217),
(75, 'animal_composite', '动物综合', '收录除上述子分区外，其余动物相关视频以及非动物主体或多个动物主体的动物相关延伸内容', '/v/animal/animal_composite', 217),
(119, 'kichiku', '鬼畜(主分区)', '', '/v/kichiku', 0),
(22, 'guide', '鬼畜调教', '使用素材在音频、画面上做一定处理，达到与bgm一定的同步感', '/v/kichiku/guide', 119),
(26, 'mad', '音MAD', '使用素材音频进行一定的二次创作来达到还原原曲的非商业性质稿件', '/v/kichiku/mad/v/kichiku/mad', 119),
(126, 'manual_vocaloid', '人力VOCALOID', '将人物或者角色的无伴奏素材进行人工调音，使其就像VOCALOID一样歌唱的技术', '/v/kichiku/manual_vocaloid', 119),
(216, 'theatre', '鬼畜剧场', '使用素材进行人工剪辑编排的有剧情的作品', '/v/kichiku/theatre', 119),
(127, 'course', '教程演示', '鬼畜相关的科普和教程演示', '/v/kichiku/course', 119),
(155, 'fashion', '时尚(主分区)', '', '/v/fashion', 0),
(157, 'makeup', '美妆护肤', '彩妆护肤、美甲美发、仿妆、医美相关内容分享或产品测评', '/v/fashion/makeup', 155),
(252, 'cos', '仿妆cos', '对二次元、三次元人物角色进行模仿、还原、展示、演绎的内容', '/v/fashion/cos', 155),
(158, 'clothing', '穿搭', '穿搭风格、穿搭技巧的展示分享，涵盖衣服、鞋靴、箱包配件、配饰（帽子、钟表、珠宝首饰）等', '/v/fashion/clothing', 155),
(159, 'catwalk', '时尚潮流', '时尚街拍、时装周、时尚大片，时尚品牌、潮流等行业相关记录及知识科普', '/v/fashion/catwalk', 155),
(192, 'trends', '风尚标(已下线)', '时尚明星专访、街拍、时尚购物相关知识科普', '/v/fashion/trends', 155),
(202, 'information', '资讯(主分区)', '', '/v/information', 0),
(203, 'hotspot', '热点', '全民关注的时政热门资讯', '/v/information/hotspot', 202),
(204, 'global', '环球', '全球范围内发生的具有重大影响力的事件动态', '/v/information/global', 202),
(205, 'social', '社会', '日常生活的社会事件、社会问题、社会风貌的报道', '/v/information/social', 202),
(206, 'multiple', '综合', '除上述领域外其它垂直领域的综合资讯', '/v/information/multiple', 202),
(165, 'ad', '广告(主分区)', '', '/v/ad', 0),
(166, 'ad', '广告(已下线)', '', '/v/ad/ad', 165),
(5, 'ent', '娱乐(主分区)', '', '/v/ent', 0),
(71, 'variety', '综艺', '所有综艺相关，全部一手掌握！', '/v/ent/variety', 5),
(241, 'talker', '娱乐杂谈', '娱乐人物解读、娱乐热点点评、娱乐行业分析', '/v/ent/talker', 5),
(242, 'fans', '粉丝创作', '粉丝向创作视频', '/v/ent/fans', 5),
(137, 'celebrity', '明星综合', '娱乐圈动态、明星资讯相关', '/v/ent/celebrity', 5),
(131, 'korea', 'Korea相关(已下线)', 'Korea相关音乐、舞蹈、综艺等视频', '/v/ent/korea', 5),
(181, 'cinephile', '影视(主分区)', '', '/v/cinephile', 0),
(182, 'cinecism', '影视杂谈', '影视评论、解说、吐槽、科普等', '/v/cinephile/cinecism', 181),
(183, 'montage', '影视剪辑', '对影视素材进行剪辑再创作的视频', '/v/cinephile/montage', 181),
(85, 'shortfilm', '小剧场', '有场景、有剧情的演绎类内容', '/v/cinephile/shortfilm', 181),
(184, 'trailer_info', '预告·资讯', '影视类相关资讯，预告，花絮等视频', '/v/cinephile/trailer_info', 181),
(177, 'documentary', '纪录片(主分区)', '', '/documentary', 0),
(37, 'history', '人文·历史', '除宣传片、影视剪辑外的，人文艺术历史纪录剧集或电影、预告、花絮、二创、5分钟以上纪录短片', '/v/documentary/history', 177),
(178, 'science', '科学·探索·自然', '除演讲、网课、教程外的，科学探索自然纪录剧集或电影、预告、花絮、二创、5分钟以上纪录短片', '/v/documentary/science', 177),
(179, 'military', '军事', '除时政军事新闻外的，军事纪录剧集或电影、预告、花絮、二创、5分钟以上纪录短片', '/v/documentary/military', 177),
(180, 'travel', '社会·美食·旅行', '除VLOG、风光摄影外的，社会美食旅行纪录剧集或电影、预告、花絮、二创、5分钟以上纪录短片', '/v/documentary/travel', 177),
(23, 'movie', '电影(主分区)', '', '/movie', 0),
(147, 'chinese', '华语电影', '', '/v/movie/chinese', 23),
(145, 'west', '欧美电影', '', '/v/movie/west', 23),
(146, 'japan', '日本电影', '', '/v/movie/japan', 23),
(83, 'movie', '其他国家', '', '/v/movie/movie', 23),
(11, 'tv', '电视剧(主分区)', '', '/tv', 0),
(185, 'mainland', '国产剧', '', '/v/tv/mainland', 11),
(187, 'overseas', '海外剧', '', '/v/tv/overseas', 11);